import { ChatContextProvider } from "./context/ChatContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-violet-200 flex items-center justify-center h-screen">
        <ChatContextProvider>{children}</ChatContextProvider>
      </body>
    </html>
  );
}
